// flow-typed signature: 7148de90071252bd7fd5d6f6f9d62bbb
// flow-typed version: <<STUB>>/react-native-swipe-gestures_v1.0.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-swipe-gestures'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-swipe-gestures' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-swipe-gestures/index' {
  declare module.exports: $Exports<'react-native-swipe-gestures'>;
}
declare module 'react-native-swipe-gestures/index.js' {
  declare module.exports: $Exports<'react-native-swipe-gestures'>;
}
