version: "3"

services:
  db:
    networks:
      - backend
    image: mongo:latest
    volumes:
      - db_data:/var/lib/mongo
    restart: always
    ports:
      - 27017:27017

  prometheus:
    networks:
      - backend
    image: quay.io/prometheus/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - "./deploy/prometheus.yml:/etc/prometheus/prometheus.yml"

  suggestions:
    networks:
      - backend
    depends_on:
      - db
    image: chanceeakin/suggestion-server:0.1.2
    ports:
      - 80:8000
    restart: always
    build: .
    links:
      - db

volumes:
  db_data:

networks:
  backend:
