version: '3.4'

services:
  api:
    container_name: goapi
    image: chanceeakin/goapi
    build:
      context: .
      dockerfile: Server.Dockerfile
    ports:
      - '8080:8080'
    environment:
      - GO_PS_USER=root
      - GO_PS_PASSWORD=goyeah
      - GO_PS_HOST=mysql
      - GO_PS_PORT=3306
    depends_on:
      - mysql
    networks:
      - chance

  mysql:
    container_name: gosql
    image: chanceeakin/gosql
    build:
        context: ./data
        dockerfile: Mysql.Dockerfile
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=goyeah
    entrypoint: /local-run-db.sh
    volumes:
      - ./data/local-run-db.sh:/local-run-db.sh
    networks:
      - chance


networks:
  chance:
    driver: bridge
