apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: suggestions
  name: suggestions
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: suggestions
    spec:
      containers:
      - image: chanceeakin/suggestion-server:0.1.0
        name: suggestions
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
