export const APP_FONT_LOAD: string = 'APP_FONT_LOAD'

export const LOGIN_USERNAME_CHANGE: string = 'LOGIN_USERNAME_CHANGE'
export const LOGIN_PASSWORD_CHANGE: string = 'LOGIN_PASSWORD_CHANGE'
export const LOGIN_SEND_BEGIN: string = 'LOGIN_SEND_BEGIN'
export const LOGIN_SEND_SUCCESS: string = 'LOGIN_SEND_SUCCESS'
export const LOGIN_SEND_FAIL: string = 'LOGIN_SEND_FAIL'

export const SIGNUP_FIRSTNAME_CHANGE: string = 'SIGNUP_FIRSTNAME_CHANGE'
export const SIGNUP_LASTNAME_CHANGE: string = 'SIGNUP_LASTNAME_CHANGE'
export const SIGNUP_EMAIL_CHANGE: string = 'SIGNUP_EMAIL_CHANGE'
export const SIGNUP_PASSWORD_CHANGE: string = 'SIGNUP_PASSWORD_CHANGE'
export const SIGNUP_SEND_BEGIN: string = 'SIGNUP_SEND_BEGIN'
export const SIGNUP_SEND_SUCCESS: string = 'SIGNUP_SEND_SUCCESS'
export const SIGNUP_SEND_FAIL: string = 'SIGNUP_SEND_FAIL'

export const SUGGESTION_FETCH_BEGIN: string = 'SUGGESTION_FETCH_BEGIN'
export const SUGGESTION_FETCH_SUCCESS: string = 'SUGGESTION_FETCH_SUCCESS'
export const SUGGESTION_FETCH_FAIL: string = 'SUGGESTION_FETCH_FAIL'
