export const APP_FONT_LOAD = 'APP_FONT_LOAD'

export const LOGIN_USERNAME_CHANGE = 'LOGIN_USERNAME_CHANGE'
export const LOGIN_PASSWORD_CHANGE = 'LOGIN_PASSWORD_CHANGE'
export const LOGIN_SEND_BEGIN = 'LOGIN_SEND_BEGIN'
export const LOGIN_SEND_SUCCESS = 'LOGIN_SEND_SUCCESS'
export const LOGIN_SEND_FAIL = 'LOGIN_SEND_FAIL'

export const SIGNUP_USERNAME_CHANGE = 'SIGNUP_USERNAME_CHANGE'
export const SIGNUP_EMAIL_CHANGE = 'SIGNUP_EMAIL_CHANGE'
export const SIGNUP_PASSWORD_CHANGE = 'SIGNUP_PASSWORD_CHANGE'
export const SIGNUP_SEND_BEGIN = 'SIGNUP_SEND_BEGIN'
export const SIGNUP_SEND_SUCCESS = 'SIGNUP_SEND_SUCCESS'
export const SIGNUP_SEND_FAIL = 'SIGNUP_SEND_FAIL'
