export const LOGIN_USERNAME_CHANGE = 'LOGIN_USERNAME_CHANGE'
export const LOGIN_PASSWORD_CHANGE = 'LOGIN_PASSWORD_CHANGE'

export const SIGNUP_USERNAME_CHANGE = 'SIGNUP_USERNAME_CHANGE'
export const SIGNUP_PASSWORD_CHANGE = 'SIGNUP_PASSWORD_CHANGE'
